#!/bin/bash # shebang to enable vi syntax coloring

# Required files
SHELLRC_REQUIRED=(
	"$HOME/.birthday"
	"$HOME/.todo"
	"$HOME/.calendar/calendar.asatru"
	"$SHELLRCDIR/bin/calendar2"
	"$SHELLRCDIR/bin/datediff"
)

# Session origin
if [ -z "$SESSION_ORIGIN" ]
then
	if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]
	then
		SESSION_ORIGIN='ssh'
	else
		SESSION_ORIGIN='local'
	fi

	# SSH preprompt
	if [[ "$SESSION_ORIGIN" = 'ssh' ]]
	then
		PREPROMPT=">$PREPROMPT"
	fi
fi

